/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.socialmedia.views;

import com.socialmedia.dao.Dao;
import com.socialmedia.domain.Image;
import com.socialmedia.domain.Post;
import com.socialmedia.domain.Profile;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Date;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jnafilechooser.api.JnaFileChooser;

public class AddPostWindow extends javax.swing.JFrame {

    private byte[] fotoCargadaBytes; 
    private String imageName;
    
    private Profile loggedProfile;
    private HomeWindow homeWindow;
    
    /**
     * Creates new form AddPostWindow
     */
    public AddPostWindow() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    public AddPostWindow(Profile loggedProfile, HomeWindow homeWindow) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.homeWindow = homeWindow;
        this.loggedProfile = loggedProfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        containerPreview = new RoundedPanel(20);
        labelIconAdd = new javax.swing.JLabel();
        labelAddPhotos = new javax.swing.JLabel();
        panelImagePreview = new PanelImageRedondeado();
        containerInput = new RoundedPanel(20);
        fieldTittle = new javax.swing.JTextField();
        buttonPost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 102));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Crear publicacion");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setBorder(null);

        textDescription.setBackground(new java.awt.Color(255, 255, 255));
        textDescription.setColumns(20);
        textDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textDescription.setLineWrap(true);
        textDescription.setRows(5);
        textDescription.setText("Escribe lo que estas pensando");
        textDescription.setBorder(null);
        jScrollPane1.setViewportView(textDescription);

        containerPreview.setBackground(new java.awt.Color(244, 244, 244));
        containerPreview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        containerPreview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                containerPreviewMouseClicked(evt);
            }
        });
        containerPreview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIconAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add-photo.png"))); // NOI18N
        containerPreview.add(labelIconAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 80, -1, -1));

        labelAddPhotos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelAddPhotos.setForeground(new java.awt.Color(102, 102, 102));
        labelAddPhotos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddPhotos.setText("Agregar fotos");
        containerPreview.add(labelAddPhotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 118, 264, 38));

        javax.swing.GroupLayout panelImagePreviewLayout = new javax.swing.GroupLayout(panelImagePreview);
        panelImagePreview.setLayout(panelImagePreviewLayout);
        panelImagePreviewLayout.setHorizontalGroup(
            panelImagePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelImagePreviewLayout.setVerticalGroup(
            panelImagePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        containerPreview.add(panelImagePreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 210));

        containerInput.setBackground(new java.awt.Color(244, 244, 244));

        fieldTittle.setBackground(new java.awt.Color(244, 244, 244));
        fieldTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fieldTittle.setForeground(new java.awt.Color(102, 102, 102));
        fieldTittle.setText("Agregar un titulo a tu publicacion");
        fieldTittle.setBorder(null);
        fieldTittle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout containerInputLayout = new javax.swing.GroupLayout(containerInput);
        containerInput.setLayout(containerInputLayout);
        containerInputLayout.setHorizontalGroup(
            containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldTittle)
                .addContainerGap())
        );
        containerInputLayout.setVerticalGroup(
            containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonPost.setBackground(new java.awt.Color(0, 102, 153));
        buttonPost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPost.setForeground(new java.awt.Color(255, 255, 255));
        buttonPost.setText("Publicar");
        buttonPost.setBorderPainted(false);
        buttonPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(containerInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(buttonPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(containerPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(containerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(containerPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPost, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void containerPreviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_containerPreviewMouseClicked
        // TODO add your handling code here:
        // Open the file  chooser
        
        JnaFileChooser fileChooser = new JnaFileChooser();
        if (fileChooser.showOpenDialog(this)) {
            try {
                String imagePath = fileChooser.getSelectedFile().toPath().toString();
                File foto = new File(imagePath);

                this.fotoCargadaBytes = Files.readAllBytes(foto.toPath());
                // Cargamos la foto
                this.panelImagePreview.setIcon(new ImageIcon(this.fotoCargadaBytes));

                // Set the name of the image
                this.imageName = foto.getName().split("\\.")[0] + "_" + System.currentTimeMillis() + "." + foto.getName().split("\\.")[1];

                this.panelImagePreview.revalidate();
                this.panelImagePreview.repaint();
                
                this.labelIconAdd.setVisible(false);
                this.labelAddPhotos.setVisible(false);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al cargar la foto seleccionada");
                System.out.println("Error al cargar la foto: " + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_containerPreviewMouseClicked

    private void buttonPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPostActionPerformed
        // TODO add your handling code here:
        
        // Get post data
        String tittle = this.fieldTittle.getText();
        String description = this.textDescription.getText();

        // Create post
        Post post = new Post(tittle, description, this.loggedProfile.getIdProfile());
        
        // Save image in the folder images in the project root
        String imagePath = "images/" + this.imageName;
        File imageFile = new File(imagePath);
        try {
            Files.write(imageFile.toPath(), this.fotoCargadaBytes);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar la imagen");
            System.out.println("Error al guardar la imagen en los archivos: " + e.getMessage());
            return;
        }
        // Create image
        Image image = new Image(this.imageName, new Date(), post.getIdPost());
        // Save image
        if (!Dao.saveImage(image)) {
            JOptionPane.showMessageDialog(null, "Error al guardar la imagen");
            System.out.println("Error al guardar la imagen en el archivo");
            return;
        }
        
        // Save post
        if (!Dao.savePost(post)) {
            JOptionPane.showMessageDialog(null, "Error al guardar la publicacion");
            System.out.println("Error al guardar la publicacion en el archivo");
            return;
        }
        
        // Show success message
        JOptionPane.showMessageDialog(null, "Publicacion creada con exito");
        // Close window
        this.homeWindow.initMyPostsData();
        this.dispose();
        
    }//GEN-LAST:event_buttonPostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPostWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPostWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPostWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPostWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPostWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPost;
    private javax.swing.JPanel containerInput;
    private javax.swing.JPanel containerPreview;
    private javax.swing.JTextField fieldTittle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAddPhotos;
    private javax.swing.JLabel labelIconAdd;
    private javax.swing.JLabel labelName;
    private org.edisoncor.gui.panel.PanelImage panelImagePreview;
    private javax.swing.JTextArea textDescription;
    // End of variables declaration//GEN-END:variables
}
