/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.socialmedia.views;

import com.socialmedia.dao.Dao;
import com.socialmedia.domain.FriendShip;
import com.socialmedia.domain.Image;
import com.socialmedia.domain.Profile;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.ImageIcon;

public class PanelFriendShip extends javax.swing.JPanel {

    private FriendShip friendShip;
    
    /**
     * Creates new form PanelFriendShip
     */
    public PanelFriendShip() {
        initComponents();
    }
    
    public PanelFriendShip(FriendShip friendShip) {
        initComponents();
        
        this.friendShip = friendShip;
        
        initData();
    }
    
    private void initData() {
        
        // Init the data for the given friend
        Profile friendProf = Dao.getProfileById(this.friendShip.getFriendId().toString());
        
        this.labelName.setText(friendProf.getName() + " " + friendProf.getLastName());
        
        // Load the profile image if exists
        // Get the profile image if exists
        if (friendProf.getProfileImageId() != null) {
            Image image = Dao.getImageById(friendProf.getProfileImageId().toString());
            
            File foto = new File("images/" + image.getImage_path());
            
            try {
                byte[] fotoBytes = Files.readAllBytes(foto.toPath());

                this.panelImageProfile.setIcon(new ImageIcon(fotoBytes));

                this.panelImageProfile.revalidate();
                this.panelImageProfile.repaint();

            } catch (IOException ex) {
                System.out.println("Error al obtener la imagen del arhivo");
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupOptions = new javax.swing.JPopupMenu();
        itemBloquear = new javax.swing.JMenuItem();
        panelImageProfile = new PanelImageRedondeado();
        labelName = new javax.swing.JLabel();
        buttonOptions = new javax.swing.JButton();

        popupOptions.setBackground(new java.awt.Color(255, 255, 255));

        itemBloquear.setBackground(new java.awt.Color(255, 255, 255));
        itemBloquear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemBloquear.setForeground(new java.awt.Color(153, 0, 0));
        itemBloquear.setText("Bloquear");
        popupOptions.add(itemBloquear);

        setBackground(new java.awt.Color(244, 244, 244));

        panelImageProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DefaultPerson.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImageProfileLayout = new javax.swing.GroupLayout(panelImageProfile);
        panelImageProfile.setLayout(panelImageProfileLayout);
        panelImageProfileLayout.setHorizontalGroup(
            panelImageProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelImageProfileLayout.setVerticalGroup(
            panelImageProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 102));
        labelName.setText("Nombre amigo");

        buttonOptions.setBackground(new java.awt.Color(244, 244, 244));
        buttonOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-options.png"))); // NOI18N
        buttonOptions.setBorderPainted(false);
        buttonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelImageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(buttonOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionsActionPerformed
        // TODO add your handling code here:
        
        this.popupOptions.show(this.buttonOptions, 0, this.buttonOptions.getHeight());
    }//GEN-LAST:event_buttonOptionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOptions;
    private javax.swing.JMenuItem itemBloquear;
    private javax.swing.JLabel labelName;
    private org.edisoncor.gui.panel.PanelImage panelImageProfile;
    private javax.swing.JPopupMenu popupOptions;
    // End of variables declaration//GEN-END:variables
}
