/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.socialmedia.views;

import com.socialmedia.dao.Dao;
import com.socialmedia.domain.FriendRequest;
import com.socialmedia.domain.Image;
import com.socialmedia.domain.Profile;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class PanelPerson extends RoundedPanel {

    private Profile profile;
    
    private Profile profileLogged;
    private HomeWindow homeWindow;
    
    /**
     * Creates new form PanelPerson
     */
    public PanelPerson() {
        super(20);
        initComponents();
    }
    
    public PanelPerson(Profile profile, Profile profileLogged, HomeWindow homeWindow) {
        super(20);
        initComponents();
        
        this.profile = profile;
        this.profileLogged = profileLogged;
        this.homeWindow = homeWindow;
        
        initData();
    }
    
    private void initData() {
        
        this.labelName.setText(this.profile.getName() + " " + this.profile.getLastName());
        
        String address = this.profile.getAddress();
        this.labelAddress.setText(address == null ? "" : "Vive en " + address);
        
        // Check if the profile is already a friend
        if (Dao.isFriend(this.profileLogged.getIdProfile().toString(), this.profile.getIdProfile().toString())) {
            this.btnAddFriend.setVisible(false);
            this.labelAddress.setText("Ya son amigos!");
        } else if (Dao.isFriendRequestRejected(this.profileLogged.getIdProfile().toString(), this.profile.getIdProfile().toString())) {
            this.btnAddFriend.setVisible(false);
            this.labelAddress.setText("Lo siento, esta persona  no quiere ser tu amigo :(");
        } else if (Dao.isFriendRequestSent(this.profileLogged.getIdProfile().toString(), this.profile.getIdProfile().toString())) {
            this.btnAddFriend.setVisible(false);
            this.labelAddress.setText("Solicitud de amistad enviada!");            
        } else if (Dao.isFriendRequestSent(this.profile.getIdProfile().toString(), this.profileLogged.getIdProfile().toString())) {
            this.btnAddFriend.setVisible(false);
            this.labelAddress.setText("Ya tienes una solicitud de esta persona, aceptala!");
        }
        
        // Get the profile image if exists
        if (this.profile.getProfileImageId() != null) {
            Image image = Dao.getImageById(this.profile.getProfileImageId().toString());
            
            File foto = new File("images/" + image.getImage_path());
            
            try {
                byte[] fotoBytes = Files.readAllBytes(foto.toPath());

                this.panelImageProfile.setIcon(new ImageIcon(fotoBytes));

                this.panelImageProfile.revalidate();
                this.panelImageProfile.repaint();

            } catch (IOException ex) {
                System.out.println("Error al obtener la imagen del arhivo");
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImageProfile = new PanelImageRedondeado();
        labelName = new javax.swing.JLabel();
        btnAddFriend = new javax.swing.JButton();
        labelAddress = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panelImageProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DefaultPerson.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImageProfileLayout = new javax.swing.GroupLayout(panelImageProfile);
        panelImageProfile.setLayout(panelImageProfileLayout);
        panelImageProfileLayout.setHorizontalGroup(
            panelImageProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        panelImageProfileLayout.setVerticalGroup(
            panelImageProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        labelName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 102));
        labelName.setText("Juan Perez de la Garza");

        btnAddFriend.setBackground(new java.awt.Color(0, 102, 153));
        btnAddFriend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddFriend.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFriend.setText("Agregar amigo");
        btnAddFriend.setBorderPainted(false);
        btnAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFriendActionPerformed(evt);
            }
        });

        labelAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelAddress.setForeground(new java.awt.Color(102, 102, 102));
        labelAddress.setText("Vive en Morelia, Michoacan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelImageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        // TODO add your handling code here:
        String message = JOptionPane.showInputDialog(null, "Deseas agregar un mensaje a enviar con la solicitud?. En caso de que no solo dejalo vacio");
        
        if (message == null || message.isEmpty() || message.isBlank()) {
            message = "";
        }
        
        // Create the firend request between the logged user and the other profile
        FriendRequest friendReq = new FriendRequest(
                this.profileLogged.getIdProfile(), 
                this.profile.getIdProfile(), 
                false, 
                false, 
                new Date(), 
                message
        );
        
        if (Dao.saveFriendRequest(friendReq)) {
            JOptionPane.showMessageDialog(null, "Solicitud enviada correctamente");
            this.homeWindow.initPersonsData();
        } else {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al enviar la solicitud, intentalo mas tarde");
        }
    }//GEN-LAST:event_btnAddFriendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelName;
    private org.edisoncor.gui.panel.PanelImage panelImageProfile;
    // End of variables declaration//GEN-END:variables
}
