/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.socialmedia.diseno;

import com.socialmedia.manejoarchivos.ManejoArchivos;
import com.socialmedia.modelos.Foto;
import com.socialmedia.modelos.Perfil;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CruzZ
 */
public class EditarPerfil extends javax.swing.JFrame {

    private Perfil profile;
    private byte[] fotoCargadaBytes;
    private String imageName;
    private boolean imageChanged = false;
    /**
     * Creates new form EditProfileWindow
     */
    public EditarPerfil() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    
    public EditarPerfil(Perfil profile) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.profile = profile;
        initData();
    }
    
    private void initData(){
        
        
        this.labelName.setText(this.profile.getName() + " " + this.profile.getLastName());
        this.fieldName.setText(this.profile.getName());
        this.fieldAddress.setText(this.profile.getAddress());
        this.fieldPhone.setText(this.profile.getPhoneNumber());
        
        // Load image data
        
        // Load the profile image if exists
        // Get the profile image if exists
        if (this.profile.getProfileImageId() != null) {
            Foto image = ManejoArchivos.getImageById(this.profile.getProfileImageId().toString());
            
            File foto = new File("images/" + image.getImage_path());
            this.imageName = image.getImage_path();
            
            try {
                byte[] fotoBytes = Files.readAllBytes(foto.toPath());
                this.fotoCargadaBytes = fotoBytes;

                this.panelImagePreview.setIcon(new ImageIcon(fotoBytes));

                this.panelImagePreview.revalidate();
                this.panelImagePreview.repaint();

            } catch (IOException ex) {
                System.out.println("Error al obtener la imagen del arhivo");
            }
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        panelImagePreview = new org.edisoncor.gui.panel.PanelImage();
        containerInput = new JPanel();
        fieldName = new javax.swing.JTextField();
        containerInput2 = new JPanel();
        fieldAddress = new javax.swing.JTextField();
        containerInput4 = new JPanel();
        fieldPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEditImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 102));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelName.setText("Juan Perez");

        panelImagePreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/DefaultPerson.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImagePreviewLayout = new javax.swing.GroupLayout(panelImagePreview);
        panelImagePreview.setLayout(panelImagePreviewLayout);
        panelImagePreviewLayout.setHorizontalGroup(
            panelImagePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
        panelImagePreviewLayout.setVerticalGroup(
            panelImagePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        containerInput.setBackground(new java.awt.Color(255, 255, 255));

        fieldName.setBackground(new java.awt.Color(255, 255, 255));
        fieldName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fieldName.setForeground(new java.awt.Color(102, 102, 102));
        fieldName.setText("Nombre");
        fieldName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout containerInputLayout = new javax.swing.GroupLayout(containerInput);
        containerInput.setLayout(containerInputLayout);
        containerInputLayout.setHorizontalGroup(
            containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerInputLayout.setVerticalGroup(
            containerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        containerInput2.setBackground(new java.awt.Color(255, 255, 255));

        fieldAddress.setBackground(new java.awt.Color(255, 255, 255));
        fieldAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fieldAddress.setForeground(new java.awt.Color(102, 102, 102));
        fieldAddress.setText("Direccion");
        fieldAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout containerInput2Layout = new javax.swing.GroupLayout(containerInput2);
        containerInput2.setLayout(containerInput2Layout);
        containerInput2Layout.setHorizontalGroup(
            containerInput2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInput2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldAddress)
                .addContainerGap())
        );
        containerInput2Layout.setVerticalGroup(
            containerInput2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInput2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        containerInput4.setBackground(new java.awt.Color(255, 255, 255));

        fieldPhone.setBackground(new java.awt.Color(255, 255, 255));
        fieldPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fieldPhone.setForeground(new java.awt.Color(102, 102, 102));
        fieldPhone.setText("4422553322");
        fieldPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout containerInput4Layout = new javax.swing.GroupLayout(containerInput4);
        containerInput4.setLayout(containerInput4Layout);
        containerInput4Layout.setHorizontalGroup(
            containerInput4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInput4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldPhone)
                .addContainerGap())
        );
        containerInput4Layout.setVerticalGroup(
            containerInput4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInput4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Direccion");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nombre");

        btnSave.setBackground(new java.awt.Color(0, 102, 153));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEditImage.setBackground(new java.awt.Color(255, 255, 255));
        btnEditImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-editimage.png"))); // NOI18N
        btnEditImage.setBorderPainted(false);
        btnEditImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(304, 304, 304))
                                .addComponent(containerInput4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(containerInput2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(containerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(304, 304, 304)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditImage)
                            .addComponent(panelImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerInput4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditImageActionPerformed
        // TODO add your handling code here:

        // Open the file  chooser

        int resultado = this.jFileChooser1.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File foto = this.jFileChooser1.getSelectedFile();
            try {
                // Leer bytes de la imagen
                this.fotoCargadaBytes = Files.readAllBytes(foto.toPath());

                // Mostrar preview
                this.panelImagePreview.setIcon(new ImageIcon(this.fotoCargadaBytes));

                // Generar nombre único
                String nombreOriginal = foto.getName();
                String extension = nombreOriginal.substring(nombreOriginal.lastIndexOf('.') + 1);
                String baseName   = nombreOriginal.substring(0, nombreOriginal.lastIndexOf('.'));
                this.imageName    = String.format("%s_%d.%s",
                                        baseName,
                                        System.currentTimeMillis(),
                                        extension);

                // Refrescar el panel
                this.panelImagePreview.revalidate();
                this.panelImagePreview.repaint();

                this.imageChanged = true;
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al cargar la foto seleccionada");
                System.out.println("Error al cargar la foto: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btnEditImageActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        // Get the data from the inputs

        String name = this.fieldName.getText();
        String address = this.fieldAddress.getText();
        String phoneNumb =  this.fieldPhone.getText();

        this.profile.setName(name);
        this.profile.setAddress(address);
        this.profile.setPhoneNumber(phoneNumb);

        if (imageChanged) {
            // Save image in the folder images in the project root
            String imagePath = "images/" + this.imageName;
            File imageFile = new File(imagePath);
            try {
                Files.write(imageFile.toPath(), this.fotoCargadaBytes);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al guardar la imagen");
                System.out.println("Error al guardar la imagen en los archivos: " + e.getMessage());
                return;
            }
            // Create image
            Foto image = new Foto(this.imageName, new Date());
            // Save image
            if (!ManejoArchivos.saveImage(image)) {
                JOptionPane.showMessageDialog(null, "Error al guardar la imagen");
                System.out.println("Error al guardar la imagen en el archivo");
                return;
            }

            this.profile.setProfileImageId(image.getIdImage());
        }

        if (ManejoArchivos.updateProfile(this.profile.getIdProfile().toString(), this.profile)) {
            JOptionPane.showMessageDialog(null, "Perfil actualizado exitosamente");

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al actualizar tu perfil");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel containerInput;
    private javax.swing.JPanel containerInput2;
    private javax.swing.JPanel containerInput4;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelName;
    private org.edisoncor.gui.panel.PanelImage panelImagePreview;
    // End of variables declaration//GEN-END:variables
}
