/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.socialmedia.diseno;

import com.socialmedia.manejoarchivos.ManejoArchivos;
import com.socialmedia.modelos.Solicitud;
import com.socialmedia.modelos.Foto;
import com.socialmedia.modelos.Perfil;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author CruzZ
 */
public class PanelPersonas extends JPanel {

    private Perfil profile;
    
    private Perfil profileLogged;
    private InicioPantalla homeWindow;
    
    /**
     * Creates new form PanelPerson
     */
    public PanelPersonas() {
        initComponents();
    }
    
    public PanelPersonas(Perfil profile, Perfil profileLogged, InicioPantalla homeWindow) {
        initComponents();
        
        this.profile = profile;
        this.profileLogged = profileLogged;
        this.homeWindow = homeWindow;
        
        initData();
    }
    
    private void initData() {
        
        this.labelName.setText(this.profile.getName() + " " + this.profile.getLastName());
        
        String address = this.profile.getAddress();
        this.labelAddress.setText(address == null ? "" : "Vive en " + address);
        
        // Check if the profile is already a friend
        if (ManejoArchivos.isFriend(this.profileLogged.getIdProfile().toString(), this.profile.getIdProfile().toString())) {
            this.btnAddFriend.setVisible(false);
            this.labelAddress.setText("Ya son amigos!");
        } else if (ManejoArchivos.isFriendRequestRejected(this.profileLogged.getIdProfile().toString(), this.profile.getIdProfile().toString())) {
            this.btnAddFriend.setVisible(false);
            this.labelAddress.setText("Lo siento, esta persona  no quiere ser tu amigo :(");
        } else if (ManejoArchivos.isFriendRequestSent(this.profileLogged.getIdProfile().toString(), this.profile.getIdProfile().toString())) {
            this.btnAddFriend.setVisible(false);
            this.labelAddress.setText("Solicitud de amistad enviada!");            
        } else if (ManejoArchivos.isFriendRequestSent(this.profile.getIdProfile().toString(), this.profileLogged.getIdProfile().toString())) {
            this.btnAddFriend.setVisible(false);
            this.labelAddress.setText("Ya tienes una solicitud de esta persona, aceptala!");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        btnAddFriend = new javax.swing.JButton();
        labelAddress = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        labelName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 102));
        labelName.setText("Juan Perez de la Garza");

        btnAddFriend.setBackground(new java.awt.Color(0, 102, 153));
        btnAddFriend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddFriend.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFriend.setText("Enviar solicitud");
        btnAddFriend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFriendActionPerformed(evt);
            }
        });

        labelAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelAddress.setForeground(new java.awt.Color(102, 102, 102));
        labelAddress.setText("Vive en Morelia, Michoacan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddFriend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        // TODO add your handling code here:
        
        
        // Create the firend request between the logged user and the other profile
        Solicitud friendReq = new Solicitud(
                this.profileLogged.getIdProfile(), 
                this.profile.getIdProfile(), 
                false, 
                false, 
                new Date(), 
                ""
        );
        
        if (ManejoArchivos.saveFriendRequest(friendReq)) {
            JOptionPane.showMessageDialog(null, "Solicitud enviada correctamente");
            this.homeWindow.initPersonsData();
        } else {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al enviar la solicitud, intentalo mas tarde");
        }
    }//GEN-LAST:event_btnAddFriendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
