/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.socialmedia.diseno;

import com.socialmedia.manejoarchivos.ManejoArchivos;
import com.socialmedia.modelos.Bloquear;
import com.socialmedia.modelos.Amistad;
import com.socialmedia.modelos.Foto;
import com.socialmedia.modelos.Perfil;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author CruzZ
 */
public class PanelAmistad extends javax.swing.JPanel {

    private Amistad friendShip;
    private Perfil profileLog;
    private String fiendId;
    
    private InicioPantalla homeWindow;
    
    /**
     * Creates new form PanelFriendShip
     */
    public PanelAmistad() {
        initComponents();
    }
    
    public PanelAmistad(Amistad friendShip, Perfil profilelog, InicioPantalla homeWindow) {
        initComponents();
        
        this.friendShip = friendShip;
        this.profileLog = profilelog;
        this.homeWindow = homeWindow;
        initData();
    }
    
    private void initData() {
        
        // Init the data for the given friend
        String friendId = this.profileLog.getIdProfile().toString().equals(this.friendShip.getProfileId().toString())
                ? this.friendShip.getFriendId().toString()
                : this.friendShip.getProfileId().toString();
        this.fiendId = friendId;
        
        if (ManejoArchivos.isBlockedFriend(this.profileLog.getIdProfile().toString(), friendId)) {
            this.setBackground(new Color(255, 153, 153));
            this.labelName.setForeground(Color.WHITE);
            
            this.buttonBloquear.setText("Desbloquear");
        }
        
        Perfil friendProf = ManejoArchivos.getProfileById(friendId);
        
        this.labelName.setText(friendProf.getName() + " " + friendProf.getLastName());

        
        if (ManejoArchivos.isBlockedFriend(friendId, this.profileLog.getIdProfile().toString())) {
            this.setBackground(new Color(255, 153, 153));
            this.labelName.setForeground(Color.WHITE);
            this.buttonBloquear.setEnabled(false);
//            this.labelName.setText(this.labelName.getText() + "(Te bloqueo :c)");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupOptions = new javax.swing.JPopupMenu();
        itemBloquear = new javax.swing.JMenuItem();
        labelName = new javax.swing.JLabel();
        buttonBloquear = new javax.swing.JButton();

        popupOptions.setBackground(new java.awt.Color(255, 255, 255));

        itemBloquear.setBackground(new java.awt.Color(255, 255, 255));
        itemBloquear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemBloquear.setForeground(new java.awt.Color(153, 0, 0));
        itemBloquear.setText("Bloquear");
        itemBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBloquearActionPerformed(evt);
            }
        });
        popupOptions.add(itemBloquear);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(248, 52));
        setMinimumSize(new java.awt.Dimension(248, 52));

        labelName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 102));
        labelName.setText("Nombre amigo");

        buttonBloquear.setBackground(new java.awt.Color(255, 102, 0));
        buttonBloquear.setForeground(new java.awt.Color(255, 255, 255));
        buttonBloquear.setText("Bloquear");
        buttonBloquear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBloquearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonBloquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBloquearActionPerformed
        // TODO add your handling code here:
        
        
        if (this.buttonBloquear.getText().equalsIgnoreCase("Bloquear")) {
            
            // Blocked the friend
            Perfil profileFriend = ManejoArchivos.getProfileById(this.fiendId);
            Bloquear blockedFriend = new Bloquear(this.profileLog.getIdProfile(), profileFriend.getIdProfile());
            
            if (ManejoArchivos.saveBlockedFriend(blockedFriend)) {
                this.setBackground(new Color(255, 153, 153));
                this.labelName.setForeground(Color.WHITE);

                this.buttonBloquear.setText("Desbloquear");
                JOptionPane.showMessageDialog(null, "Has bloqueado a " + profileFriend.getName());
                this.homeWindow.initHomeData();
            } else
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error al bloquear al perfil");
            
        } else if (this.buttonBloquear.getText().equalsIgnoreCase("Desbloquear")) {
            // Unblock the friend
            Perfil unblockedFriend = ManejoArchivos.getProfileById(this.fiendId);
            if (ManejoArchivos.deleteBlockedFriend(this.profileLog.getIdProfile().toString(), this.fiendId)) {
                this.setBackground(new Color(244,244,244));
                this.labelName.setForeground(new Color(60,63,65));
                
                this.buttonBloquear.setText("Bloquear");
                JOptionPane.showMessageDialog(null, "Has desbloqueado a " + unblockedFriend.getName());
                this.homeWindow.initHomeData();
            } else
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error al desbloquear al perfil");

        }
    }//GEN-LAST:event_buttonBloquearActionPerformed

    private void itemBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBloquearActionPerformed
        // TODO add your handling code here:
        
        if (this.itemBloquear.getText().equalsIgnoreCase("Bloquear")) {
            
            // Blocked the friend
            Perfil profileFriend = ManejoArchivos.getProfileById(this.fiendId);
            Bloquear blockedFriend = new Bloquear(this.profileLog.getIdProfile(), profileFriend.getIdProfile());
            
            if (ManejoArchivos.saveBlockedFriend(blockedFriend)) {
                this.setBackground(new Color(255, 153, 153));
                this.labelName.setForeground(Color.WHITE);

                this.itemBloquear.setText("Desbloquear");
                JOptionPane.showMessageDialog(null, "Has bloqueado a " + profileFriend.getName());
                this.homeWindow.initHomeData();
            } else
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error al bloquear al perfil");
            
        } else if (this.itemBloquear.getText().equalsIgnoreCase("Desbloquear")) {
            // Unblock the friend
            Perfil unblockedFriend = ManejoArchivos.getProfileById(this.fiendId);
            if (ManejoArchivos.deleteBlockedFriend(this.profileLog.getIdProfile().toString(), this.fiendId)) {
                this.setBackground(new Color(244,244,244));
                this.labelName.setForeground(new Color(60,63,65));
                
                this.itemBloquear.setText("Bloquear");
                JOptionPane.showMessageDialog(null, "Has desbloqueado a " + unblockedFriend.getName());
                this.homeWindow.initHomeData();
            } else
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error al desbloquear al perfil");

        }
        
    }//GEN-LAST:event_itemBloquearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBloquear;
    private javax.swing.JMenuItem itemBloquear;
    private javax.swing.JLabel labelName;
    private javax.swing.JPopupMenu popupOptions;
    // End of variables declaration//GEN-END:variables
}
