/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.socialmedia.diseno;

import com.socialmedia.manejoarchivos.ManejoArchivos;
import com.socialmedia.modelos.Solicitud;
import com.socialmedia.modelos.Amistad;
import com.socialmedia.modelos.Foto;
import com.socialmedia.modelos.Perfil;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author CruzZ
 */
public class PanelSolicitud extends javax.swing.JPanel {

    private Solicitud friendReq;
    
    private InicioPantalla homeWindow;
    
    /**
     * Creates new form PanelFriendShip
     */
    public PanelSolicitud() {
        initComponents();
    }
    
    public PanelSolicitud(Solicitud friendReq, InicioPantalla homeWindow) {
        initComponents();
        
        this.friendReq = friendReq;
        this.homeWindow = homeWindow;
        
        initData();
    }
    
    private void initData() {
        
        // Init the data for the given friend
        Perfil profileSender = ManejoArchivos.getProfileById(this.friendReq.getProfileReqId().toString());
        
        this.labelName.setText(profileSender.getName() + " " + profileSender.getLastName());

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupOptions = new javax.swing.JPopupMenu();
        itemBloquear = new javax.swing.JMenuItem();
        labelName = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        buttonReject = new javax.swing.JButton();

        popupOptions.setBackground(new java.awt.Color(255, 255, 255));

        itemBloquear.setBackground(new java.awt.Color(255, 255, 255));
        itemBloquear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemBloquear.setForeground(new java.awt.Color(153, 0, 0));
        itemBloquear.setText("Bloquear");
        popupOptions.add(itemBloquear);

        setBackground(new java.awt.Color(255, 255, 255));

        labelName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 102));
        labelName.setText("Nombre del solicitante");

        btnConfirm.setBackground(new java.awt.Color(0, 255, 255));
        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirmar");
        btnConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        buttonReject.setBackground(new java.awt.Color(255, 255, 255));
        buttonReject.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonReject.setForeground(new java.awt.Color(51, 51, 51));
        buttonReject.setText("Rechazar");
        buttonReject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonReject, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonReject, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        
        this.friendReq.setIsReqAccepted(true);
        
        // Update the request
        if (ManejoArchivos.updateFriendRequest(this.friendReq.getIdFriendRequest().toString(), this.friendReq)) {
            // Create the new frienshipt
            Amistad newFriendShip = new Amistad(this.friendReq.getProfileReqId(), this.friendReq.getProfielReceivedId(), new  Date());
            // Save the friend
            if (ManejoArchivos.saveFriend(newFriendShip)) {
                // Update the home lists
                JOptionPane.showMessageDialog(null, "Solicitud de amistad aceptada");
                this.homeWindow.initFriendRequests();
                this.homeWindow.initFriends();
            } else  {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error al confirmar. Intentalo mas tarde");

            }
        } else {
            JOptionPane.showConfirmDialog(null, "Ha ocurrido un error al actualizar la solicitud");
        }
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void buttonRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRejectActionPerformed
        // TODO add your handling code here:
        
        this.friendReq.setIsReqAccepted(true);
        
        // Update the request
        if (ManejoArchivos.updateFriendRequest(this.friendReq.getIdFriendRequest().toString(), this.friendReq)) {
            JOptionPane.showMessageDialog(null, "Se ha rechazado la solicitud");
            this.homeWindow.initFriendRequests();
            this.homeWindow.initFriends();
        } else {
            JOptionPane.showConfirmDialog(null, "Ha ocurrido un error al actualizar la solicitud");
        }
        
    }//GEN-LAST:event_buttonRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton buttonReject;
    private javax.swing.JMenuItem itemBloquear;
    private javax.swing.JLabel labelName;
    private javax.swing.JPopupMenu popupOptions;
    // End of variables declaration//GEN-END:variables
}
